from enum import Enum

class ChatState(Enum):
    MAIN = 1,
    PROVIDING_API_KEY = 2,
    SELECTING_ASSISTANT_ROLE = 3,
    HAVING_CONVERSATION_WITH_ASSISTANT = 4,
    PROVIDING_IMAGES_DESCRIPTION = 5,
    SELECTING_IMAGES_COUNT = 6,
    SELECTING_IMAGES_SIZE = 7,
    PROVIDING_MEDIA_FILE = 8,
    